spring:
  config:
    activate:
      on-profile: local

security:
  oauth2:
    github:
      client-id: ${OAUTH2_GITHUB_CLIENT_ID}
      client-secret: ${OAUTH2_GITHUB_CLIENT_SECRET}
      token-uri: https://github.com/login/oauth/access_token
      user-info-uri: https://api.github.com/user
    google:
      client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
      client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
      token-uri: https://oauth2.googleapis.com/token
      user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
