spring:
  config:
    activate:
      on-profile: local

security:
  oauth2:
    github:
      domain: https://github.com
      client-id: ${OAUTH2_GITHUB_CLIENT_ID}
      client-secret: ${OAUTH2_GITHUB_CLIENT_SECRET}
